/**
 * pari-market thin typed TS client.
 *
 * M1.5. No @coral-xyz/anchor dependency, matching the M0 decision already
 * recorded in validate-stat-borsh.ts (socket flagged transitive CVEs --
 * bigint-buffer high, uuid moderate -- on @coral-xyz/anchor + @solana/spl-token
 * for this workspace). Uses @solana/web3.js directly (already resolved from
 * the workspace root node_modules, same require-up-one-level pattern as
 * validate-stat-call.ts) plus a hand-rolled Borsh encoder for instruction
 * args, matching the pattern client/validate-stat-borsh.ts established for
 * the txoracle CPI arg types.
 *
 * PDA derivation for all 5 instructions' accounts, including the
 * cross-program daily_scores_roots PDA resolve() needs (owned by
 * TXORACLE_PROGRAM_ID, not this program -- see constants.rs).
 *
 * Verifier (M1.5): `npx tsc --noEmit -p client/tsconfig.json` compiles clean.
 * No live calls in this block (M3 deploys the program; devnet funding is a
 * separate M1.5 sub-task, not exercised by this file).
 */

import { PublicKey } from "@solana/web3.js";

// ── Program IDs (frozen; mirrors programs/pari-market/src/constants.rs) ────

export const PARI_MARKET_PROGRAM_ID = new PublicKey(
  "565SYmLeQ64r8kNujRpVhnfGgAybQrXz72knMyUj1xc3"
);

export const TXORACLE_PROGRAM_ID = new PublicKey(
  "6pW64gN1s2uqjHkn1unFeEjAwJkPGHoppGvS715wyP2J"
);

export const SPL_TOKEN_PROGRAM_ID = new PublicKey(
  "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
);

const SYSTEM_PROGRAM_ID = new PublicKey("11111111111111111111111111111111");
const RENT_SYSVAR_ID = new PublicKey(
  "SysvarRent111111111111111111111111111111111"
);

// ── PDA seeds (frozen; mirrors constants.rs -- no inline literals elsewhere) ─

const MARKET_SEED = Buffer.from("market");
const POSITION_SEED = Buffer.from("position");
const VAULT_SEED = Buffer.from("vault");
const DAILY_SCORES_ROOTS_SEED = Buffer.from("daily_scores_roots");

// ── PDA derivation ──────────────────────────────────────────────────────────

export function marketPda(marketId: bigint): [PublicKey, number] {
  const buf = Buffer.alloc(8);
  buf.writeBigUInt64LE(marketId, 0);
  return PublicKey.findProgramAddressSync(
    [MARKET_SEED, buf],
    PARI_MARKET_PROGRAM_ID
  );
}

export function vaultPda(market: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [VAULT_SEED, market.toBuffer()],
    PARI_MARKET_PROGRAM_ID
  );
}

export function positionPda(
  market: PublicKey,
  bettor: PublicKey
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [POSITION_SEED, market.toBuffer(), bettor.toBuffer()],
    PARI_MARKET_PROGRAM_ID
  );
}

/** Cross-program PDA: owned by TXORACLE_PROGRAM_ID, not pari-market.
 * resolve() re-derives and checks this against market.epoch_day (WrongRoot
 * on mismatch) -- see instructions/resolve.rs. */
export function dailyScoresRootsPda(epochDay: number): [PublicKey, number] {
  const buf = Buffer.alloc(2);
  buf.writeUInt16LE(epochDay, 0);
  return PublicKey.findProgramAddressSync(
    [DAILY_SCORES_ROOTS_SEED, buf],
    TXORACLE_PROGRAM_ID
  );
}

// ── Types mirroring the on-chain instruction args ───────────────────────────
// (see programs/pari-market/src/market/state.rs, cpi/txoracle.rs)

export type Comparison = "GreaterThan" | "LessThan" | "EqualTo";
export type BinaryExpression = "Add" | "Subtract";

export interface TraderPredicate {
  threshold: number; // i32
  comparison: Comparison;
}

export interface ProofNode {
  hash: number[]; // 32 bytes
  isRightSibling: boolean;
}

export interface ScoreStat {
  key: number; // u32
  value: number; // i32
  period: number; // i32
}

export interface StatTerm {
  statToProve: ScoreStat;
  eventStatRoot: number[]; // 32 bytes
  statProof: ProofNode[];
}

export interface ScoresUpdateStats {
  updateCount: number; // i32
  minTimestamp: number; // i64
  maxTimestamp: number; // i64
}

export interface ScoresBatchSummary {
  fixtureId: number; // i64
  updateStats: ScoresUpdateStats;
  eventsSubTreeRoot: number[]; // 32 bytes
}

// ── Instruction discriminators ──────────────────────────────────────────────
// Anchor's default 8-byte sighash: sha256("global:<snake_case_ix_name>")[0..8].
// Hardcoded here (not computed at runtime) to keep this client dependency-free;
// values copied verbatim from target/idl/pari_market.json's per-instruction
// "discriminator" field, generated by this session's `anchor build` against
// the current pari-market source (all 5 instructions implemented, M1/M2a/
// M2.5/M2b). Re-copy from the IDL if the program is rebuilt with a renamed
// instruction (renaming changes the sighash).

const IX_DISCRIMINATOR: Record<
  "init_market" | "deposit" | "lock_market" | "resolve" | "claim_payout",
  number[]
> = {
  init_market: [33, 253, 15, 116, 89, 25, 127, 236],
  deposit: [242, 35, 198, 137, 82, 225, 242, 182],
  lock_market: [107, 8, 184, 91, 223, 13, 180, 38],
  resolve: [246, 150, 236, 206, 108, 63, 58, 10],
  claim_payout: [127, 240, 132, 62, 227, 198, 146, 133],
};

// ── Borsh writer (matches client/validate-stat-borsh.ts's Writer exactly) ──

class Writer {
  private chunks: Buffer[] = [];
  u8(v: number): this {
    const b = Buffer.alloc(1);
    b.writeUInt8(v, 0);
    this.chunks.push(b);
    return this;
  }
  bool(v: boolean): this {
    return this.u8(v ? 1 : 0);
  }
  i32(v: number): this {
    const b = Buffer.alloc(4);
    b.writeInt32LE(v, 0);
    this.chunks.push(b);
    return this;
  }
  u32(v: number): this {
    const b = Buffer.alloc(4);
    b.writeUInt32LE(v, 0);
    this.chunks.push(b);
    return this;
  }
  u16(v: number): this {
    const b = Buffer.alloc(2);
    b.writeUInt16LE(v, 0);
    this.chunks.push(b);
    return this;
  }
  u64(v: bigint): this {
    const b = Buffer.alloc(8);
    b.writeBigUInt64LE(v, 0);
    this.chunks.push(b);
    return this;
  }
  i64(v: number | bigint): this {
    const b = Buffer.alloc(8);
    b.writeBigInt64LE(BigInt(v), 0);
    this.chunks.push(b);
    return this;
  }
  bytes32(v: number[]): this {
    if (v.length !== 32) throw new Error(`expected 32 bytes, got ${v.length}`);
    this.chunks.push(Buffer.from(v));
    return this;
  }
  raw(b: Buffer): this {
    this.chunks.push(b);
    return this;
  }
  toBuffer(): Buffer {
    return Buffer.concat(this.chunks);
  }
}

const COMPARISON_INDEX: Record<Comparison, number> = {
  GreaterThan: 0,
  LessThan: 1,
  EqualTo: 2,
};
const BINARY_EXPR_INDEX: Record<BinaryExpression, number> = {
  Add: 0,
  Subtract: 1,
};

function writeProofNode(w: Writer, n: ProofNode): void {
  w.bytes32(n.hash).bool(n.isRightSibling);
}
function writeVec<T>(
  w: Writer,
  items: T[],
  writeItem: (w: Writer, item: T) => void
): void {
  w.u32(items.length);
  for (const item of items) writeItem(w, item);
}
function writeScoreStat(w: Writer, s: ScoreStat): void {
  w.u32(s.key).i32(s.value).i32(s.period);
}
function writeStatTerm(w: Writer, t: StatTerm): void {
  writeScoreStat(w, t.statToProve);
  w.bytes32(t.eventStatRoot);
  writeVec(w, t.statProof, writeProofNode);
}
function writeScoresBatchSummary(w: Writer, s: ScoresBatchSummary): void {
  w.i64(s.fixtureId);
  w.i32(s.updateStats.updateCount)
    .i64(s.updateStats.minTimestamp)
    .i64(s.updateStats.maxTimestamp);
  w.bytes32(s.eventsSubTreeRoot);
}
function writeTraderPredicate(w: Writer, p: TraderPredicate): void {
  w.i32(p.threshold).u8(COMPARISON_INDEX[p.comparison]);
}
function writeOption<T>(
  w: Writer,
  v: T | null | undefined,
  writeItem: (w: Writer, item: T) => void
): void {
  if (v !== null && v !== undefined) {
    w.bool(true);
    writeItem(w, v);
  } else {
    w.bool(false);
  }
}

// ── AccountMeta shape (avoids depending on web3.js's TransactionInstruction
// constructor here; callers assemble the actual instruction) ───────────────

export interface AccountMetaLike {
  pubkey: PublicKey;
  isSigner: boolean;
  isWritable: boolean;
}

export interface BuiltInstruction {
  programId: PublicKey;
  keys: AccountMetaLike[];
  data: Buffer;
}

// ── init_market ──────────────────────────────────────────────────────────

export interface InitMarketArgs {
  marketId: bigint;
  fixtureId: bigint;
  epochDay: number;
  statAKey: number;
  statBKey?: number | null;
  op?: BinaryExpression | null;
  predicate: TraderPredicate;
  lockTs: bigint;
}

export interface InitMarketAccounts {
  usdcMint: PublicKey;
  authority: PublicKey;
}

/** Builds init_market. market + vault PDAs are derived internally from
 * args.marketId; caller supplies only the accounts that aren't derivable. */
export function buildInitMarket(
  args: InitMarketArgs,
  accounts: InitMarketAccounts
): BuiltInstruction {
  const [market] = marketPda(args.marketId);
  const [vault] = vaultPda(market);

  const w = new Writer();
  w.raw(Buffer.from(IX_DISCRIMINATOR.init_market));
  w.u64(args.marketId);
  w.i64(args.fixtureId);
  w.u16(args.epochDay);
  w.u32(args.statAKey);
  writeOption(w, args.statBKey, (w, v) => w.u32(v));
  writeOption(w, args.op, (w, v) => w.u8(BINARY_EXPR_INDEX[v]));
  writeTraderPredicate(w, args.predicate);
  w.i64(args.lockTs);

  return {
    programId: PARI_MARKET_PROGRAM_ID,
    keys: [
      { pubkey: market, isSigner: false, isWritable: true },
      { pubkey: accounts.usdcMint, isSigner: false, isWritable: false },
      { pubkey: vault, isSigner: false, isWritable: true },
      { pubkey: accounts.authority, isSigner: true, isWritable: true },
      { pubkey: SPL_TOKEN_PROGRAM_ID, isSigner: false, isWritable: false },
      { pubkey: SYSTEM_PROGRAM_ID, isSigner: false, isWritable: false },
      { pubkey: RENT_SYSVAR_ID, isSigner: false, isWritable: false },
    ],
    data: w.toBuffer(),
  };
}

// ── deposit ──────────────────────────────────────────────────────────────

export interface DepositArgs {
  amount: bigint;
  side: boolean;
}

export interface DepositAccounts {
  market: PublicKey;
  marketId: bigint; // needed to re-derive vault (vault PDA depends on market, not marketId directly, but market is already known here -- kept for symmetry/clarity)
  bettor: PublicKey;
  bettorUsdc: PublicKey;
}

export function buildDeposit(
  args: DepositArgs,
  accounts: DepositAccounts
): BuiltInstruction {
  const [position] = positionPda(accounts.market, accounts.bettor);
  const [vault] = vaultPda(accounts.market);

  const w = new Writer();
  w.raw(Buffer.from(IX_DISCRIMINATOR.deposit));
  w.u64(args.amount);
  w.bool(args.side);

  return {
    programId: PARI_MARKET_PROGRAM_ID,
    keys: [
      { pubkey: accounts.market, isSigner: false, isWritable: true },
      { pubkey: position, isSigner: false, isWritable: true },
      { pubkey: vault, isSigner: false, isWritable: true },
      { pubkey: accounts.bettorUsdc, isSigner: false, isWritable: true },
      { pubkey: accounts.bettor, isSigner: true, isWritable: true },
      { pubkey: SPL_TOKEN_PROGRAM_ID, isSigner: false, isWritable: false },
      { pubkey: SYSTEM_PROGRAM_ID, isSigner: false, isWritable: false },
    ],
    data: w.toBuffer(),
  };
}

// ── lock_market ──────────────────────────────────────────────────────────

export interface LockMarketAccounts {
  market: PublicKey;
  caller: PublicKey;
}

/** Permissionless: any signer may call once Clock >= market.lock_ts. */
export function buildLockMarket(
  accounts: LockMarketAccounts
): BuiltInstruction {
  const w = new Writer();
  w.raw(Buffer.from(IX_DISCRIMINATOR.lock_market));

  return {
    programId: PARI_MARKET_PROGRAM_ID,
    keys: [
      { pubkey: accounts.market, isSigner: false, isWritable: true },
      { pubkey: accounts.caller, isSigner: true, isWritable: false },
    ],
    data: w.toBuffer(),
  };
}

// ── resolve ──────────────────────────────────────────────────────────────

export interface ResolveArgs {
  ts: bigint;
  fixtureSummary: ScoresBatchSummary;
  fixtureProof: ProofNode[];
  mainTreeProof: ProofNode[];
  statA: StatTerm;
  statB?: StatTerm | null;
}

export interface ResolveAccounts {
  market: PublicKey;
  epochDay: number; // needed to derive daily_scores_merkle_roots
  caller: PublicKey;
}

/** Caller supplies ONLY proof material (Dayo M4a P0 #1 structural fix,
 * enforced on-chain in resolve()'s body): predicate/stat_a_key/stat_b_key/op
 * are read from market state, never passed here. daily_scores_merkle_roots
 * is derived cross-program under TXORACLE_PROGRAM_ID from epochDay. */
export function buildResolve(
  args: ResolveArgs,
  accounts: ResolveAccounts
): BuiltInstruction {
  const [dailyScoresMerkleRoots] = dailyScoresRootsPda(accounts.epochDay);

  const w = new Writer();
  w.raw(Buffer.from(IX_DISCRIMINATOR.resolve));
  w.i64(args.ts);
  writeScoresBatchSummary(w, args.fixtureSummary);
  writeVec(w, args.fixtureProof, writeProofNode);
  writeVec(w, args.mainTreeProof, writeProofNode);
  writeStatTerm(w, args.statA);
  writeOption(w, args.statB, writeStatTerm);

  return {
    programId: PARI_MARKET_PROGRAM_ID,
    keys: [
      { pubkey: accounts.market, isSigner: false, isWritable: true },
      { pubkey: dailyScoresMerkleRoots, isSigner: false, isWritable: false },
      { pubkey: TXORACLE_PROGRAM_ID, isSigner: false, isWritable: false },
      { pubkey: accounts.caller, isSigner: true, isWritable: false },
    ],
    data: w.toBuffer(),
  };
}

// ── claim_payout ─────────────────────────────────────────────────────────

export interface ClaimPayoutAccounts {
  market: PublicKey;
  bettor: PublicKey;
  bettorUsdc: PublicKey;
}

export function buildClaimPayout(
  accounts: ClaimPayoutAccounts
): BuiltInstruction {
  const [position] = positionPda(accounts.market, accounts.bettor);
  const [vault] = vaultPda(accounts.market);

  const w = new Writer();
  w.raw(Buffer.from(IX_DISCRIMINATOR.claim_payout));

  return {
    programId: PARI_MARKET_PROGRAM_ID,
    keys: [
      { pubkey: accounts.market, isSigner: false, isWritable: false },
      { pubkey: position, isSigner: false, isWritable: true },
      { pubkey: vault, isSigner: false, isWritable: true },
      { pubkey: accounts.bettorUsdc, isSigner: false, isWritable: true },
      { pubkey: accounts.bettor, isSigner: true, isWritable: true },
      { pubkey: SPL_TOKEN_PROGRAM_ID, isSigner: false, isWritable: false },
    ],
    data: w.toBuffer(),
  };
}
