// AUTO-GENERATED by M2a dispatch from a live TxLINE stat-validation response.
// Fixture: fixtureId=18172379, seq=1053 (M0's confirmed live fixture).
// Fetched fresh 2026-07-02 (session S175, M2a) via ~/secrets/txline-api-token.env
// against https://txline-dev.txodds.com/api/scores/stat-validation.
// epoch_day = floor(summary.updateStats.minTimestamp / 86_400_000) = 20636.
use pari_market::cpi::txoracle::{ScoreStat, ScoresBatchSummary, ScoresUpdateStats, StatTerm};
use pari_market::proof::ProofNode;

// M0 load-bearing gotcha (confirmed live, this session): `ts` MUST be
// summary.updateStats.minTimestamp, NOT the top-level `ts` field on the
// stat-validation response -- using the wrong value produces the real
// txoracle program's TimestampMismatch (custom error 6010). First-pass
// fixture generation used the top-level ts (1782957972840) and hit exactly
// this error live against the dumped txoracle.so; fixed to the correct value.
pub const TS: i64 = 1782957917000; // == summary.updateStats.minTimestamp
pub const EPOCH_DAY: u16 = 20636;
pub const FIXTURE_ID: i64 = 18172379;

pub fn fixture_summary() -> ScoresBatchSummary {
    ScoresBatchSummary {
        fixture_id: 18172379,
        update_stats: ScoresUpdateStats {
            update_count: 13,
            min_timestamp: 1782957917000,
            max_timestamp: 1782957979012,
        },
        events_sub_tree_root: [
            193, 74, 13, 205, 229, 227, 7, 100, 151, 80, 173, 186, 83, 18, 124, 229, 162, 166, 6,
            242, 25, 89, 255, 172, 122, 0, 197, 233, 143, 44, 21, 93,
        ],
    }
}

pub fn stat_a() -> StatTerm {
    StatTerm {
        stat_to_prove: ScoreStat {
            key: 1,
            value: 2,
            period: 4,
        },
        event_stat_root: [
            34, 127, 155, 116, 255, 227, 71, 230, 40, 71, 121, 68, 89, 117, 145, 113, 160, 106,
            122, 173, 22, 189, 240, 145, 78, 114, 204, 5, 139, 44, 141, 89,
        ],
        stat_proof: vec![
            ProofNode {
                hash: [
                    28, 187, 166, 171, 254, 75, 247, 123, 61, 159, 33, 129, 21, 186, 213, 245, 8,
                    120, 240, 123, 33, 97, 19, 21, 164, 82, 81, 112, 128, 181, 51, 67,
                ],
                is_right_sibling: true,
            },
            ProofNode {
                hash: [
                    124, 57, 205, 12, 215, 81, 205, 11, 72, 249, 83, 84, 239, 103, 70, 105, 15,
                    192, 92, 245, 211, 252, 137, 75, 44, 115, 166, 80, 110, 144, 4, 40,
                ],
                is_right_sibling: true,
            },
            ProofNode {
                hash: [
                    26, 213, 122, 28, 87, 250, 126, 235, 249, 40, 168, 16, 117, 50, 227, 172, 89,
                    131, 119, 28, 81, 46, 53, 183, 236, 192, 229, 234, 69, 225, 168, 45,
                ],
                is_right_sibling: true,
            },
            ProofNode {
                hash: [
                    230, 118, 239, 172, 8, 21, 73, 56, 56, 161, 126, 132, 21, 151, 53, 124, 53,
                    131, 74, 40, 178, 211, 59, 11, 202, 253, 246, 207, 114, 156, 250, 58,
                ],
                is_right_sibling: true,
            },
        ],
    }
}

pub fn stat_b() -> StatTerm {
    StatTerm {
        stat_to_prove: ScoreStat {
            key: 2,
            value: 0,
            period: 4,
        },
        event_stat_root: [
            34, 127, 155, 116, 255, 227, 71, 230, 40, 71, 121, 68, 89, 117, 145, 113, 160, 106,
            122, 173, 22, 189, 240, 145, 78, 114, 204, 5, 139, 44, 141, 89,
        ],
        stat_proof: vec![
            ProofNode {
                hash: [
                    1, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
                    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
                ],
                is_right_sibling: false,
            },
            ProofNode {
                hash: [
                    38, 62, 62, 38, 255, 255, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ],
                is_right_sibling: false,
            },
        ],
    }
}

pub fn fixture_proof() -> Vec<ProofNode> {
    vec![
        ProofNode {
            hash: [
                154, 139, 225, 78, 101, 177, 212, 35, 145, 68, 218, 18, 166, 161, 173, 74, 234,
                118, 27, 51, 74, 182, 135, 125, 121, 149, 159, 222, 245, 116, 77, 140,
            ],
            is_right_sibling: false,
        },
        ProofNode {
            hash: [
                160, 64, 233, 245, 45, 212, 55, 16, 240, 101, 202, 1, 59, 51, 186, 16, 110, 118,
                212, 233, 154, 19, 190, 23, 253, 18, 6, 121, 202, 100, 37, 1,
            ],
            is_right_sibling: false,
        },
        ProofNode {
            hash: [
                175, 165, 79, 75, 109, 80, 91, 190, 2, 20, 18, 247, 63, 27, 107, 233, 3, 130, 88,
                51, 223, 152, 118, 101, 94, 250, 52, 7, 202, 47, 45, 249,
            ],
            is_right_sibling: true,
        },
        ProofNode {
            hash: [
                197, 177, 102, 254, 149, 111, 171, 26, 86, 245, 213, 41, 134, 230, 6, 87, 3, 101,
                102, 75, 164, 225, 178, 225, 60, 177, 161, 168, 157, 49, 158, 157,
            ],
            is_right_sibling: true,
        },
        ProofNode {
            hash: [
                6, 18, 212, 65, 226, 220, 138, 34, 185, 195, 4, 245, 197, 207, 125, 232, 99, 202,
                255, 234, 27, 114, 168, 158, 156, 158, 13, 133, 135, 99, 39, 125,
            ],
            is_right_sibling: false,
        },
    ]
}

pub fn main_tree_proof() -> Vec<ProofNode> {
    vec![ProofNode {
        hash: [
            69, 149, 44, 255, 56, 252, 174, 247, 55, 89, 252, 209, 107, 242, 184, 220, 32, 41, 139,
            241, 101, 42, 168, 51, 164, 231, 229, 208, 235, 17, 127, 13,
        ],
        is_right_sibling: false,
    }]
}
